[package]
name = "mhf-file-editor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
eframe = "0.24.1"
rfd = "0.14"
egui_extras = { version = "0.27", features = ["svg"] }
native-dialog = { version = "0.5.0-alpha.1" }
encoding_rs = "0.8.32"
winit = "0.29"
ico = "0.3"
windres = "0.2.2"
byteorder = "1.4.3"
image = "0.24.7"
ctrlc = "3.4.1"
rsfrontier-core = { git = "https://github.com/Paxlord/rsfrontier.git" }
tempfile = "3.20.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bitflags = "2.9.1"

[target.'cfg(windows)'.dependencies.windows]
version = "0.48"
features = ["Win32_System_WindowsProgramming"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
