// Item patterns and helper functions based on items.hexpat

/// Item icon enum based on the pattern
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ItemIcon {
    SMOKE = 0x00,
    ORB = 0x01,
    BOMB = 0x02,
    MEAT = 0x03,
    FISH_BAIT = 0x04,
    FISH = 0x05,
    BOX = 0x06,
    WHETSTONE = 0x07,
    DUNG = 0x08,
    MONSTER = 0x09,
    BONES = 0x0A,
    BINOCULARS = 0x0B,
    MUSHROOM = 0x0C,
    BUGNET = 0x0D,
    PELT = 0x0E,
    LEAF = 0x0F,
    PICKAXE = 0x10,
    BARREL = 0x11,
    SEED = 0x12,
    BBQ_SPIT = 0x13,
    INSECT = 0x14,
    TRAP = 0x15,
    NET = 0x16,
    SCALE = 0x17,
    DRINK = 0x18,
    EGG = 0x19,
    AMMO = 0x1A,
    STONE = 0x1B,
    HUSK = 0x1C,
    MAP = 0x1D,
    FLUTE = 0x1E,
    FANG = 0x1F,
    GRID = 0x20,
    QUESTION_MARK = 0x21,
    COIN = 0x22,
    SAC = 0x23,
    BOOK = 0x24,
    TICKET = 0x25,
    KNIFE = 0x26,
    MUSIC_SHEET = 0x29,
    JEWEL = 0x2B,
    HOUSE = 0x2C,
    PLANT = 0x2D,
    MOCHA = 0x2F,
    POT = 0x30,
    BOOMERANG = 0x31,
    COATING = 0x32,
    EMPTY_BOTTLE = 0x33,
    CARAPACE = 0x34,
    SWORD_CRYSTAL = 0x4F,
    POTION = 0x50,
    FRUIT = 0x52,
    TOWER_W_SIGIL = 0x56,
    TOWER_A_SIGIL = 0x5B,
    MANTLE = 0x5C,
    ARMOR_SPHERE = 0x5D,
}

impl ItemIcon {
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            0x00 => Some(ItemIcon::SMOKE),
            0x01 => Some(ItemIcon::ORB),
            0x02 => Some(ItemIcon::BOMB),
            0x03 => Some(ItemIcon::MEAT),
            0x04 => Some(ItemIcon::FISH_BAIT),
            0x05 => Some(ItemIcon::FISH),
            0x06 => Some(ItemIcon::BOX),
            0x07 => Some(ItemIcon::WHETSTONE),
            0x08 => Some(ItemIcon::DUNG),
            0x09 => Some(ItemIcon::MONSTER),
            0x0A => Some(ItemIcon::BONES),
            0x0B => Some(ItemIcon::BINOCULARS),
            0x0C => Some(ItemIcon::MUSHROOM),
            0x0D => Some(ItemIcon::BUGNET),
            0x0E => Some(ItemIcon::PELT),
            0x0F => Some(ItemIcon::LEAF),
            0x10 => Some(ItemIcon::PICKAXE),
            0x11 => Some(ItemIcon::BARREL),
            0x12 => Some(ItemIcon::SEED),
            0x13 => Some(ItemIcon::BBQ_SPIT),
            0x14 => Some(ItemIcon::INSECT),
            0x15 => Some(ItemIcon::TRAP),
            0x16 => Some(ItemIcon::NET),
            0x17 => Some(ItemIcon::SCALE),
            0x18 => Some(ItemIcon::DRINK),
            0x19 => Some(ItemIcon::EGG),
            0x1A => Some(ItemIcon::AMMO),
            0x1B => Some(ItemIcon::STONE),
            0x1C => Some(ItemIcon::HUSK),
            0x1D => Some(ItemIcon::MAP),
            0x1E => Some(ItemIcon::FLUTE),
            0x1F => Some(ItemIcon::FANG),
            0x20 => Some(ItemIcon::GRID),
            0x21 => Some(ItemIcon::QUESTION_MARK),
            0x22 => Some(ItemIcon::COIN),
            0x23 => Some(ItemIcon::SAC),
            0x24 => Some(ItemIcon::BOOK),
            0x25 => Some(ItemIcon::TICKET),
            0x26 => Some(ItemIcon::KNIFE),
            0x29 => Some(ItemIcon::MUSIC_SHEET),
            0x2B => Some(ItemIcon::JEWEL),
            0x2C => Some(ItemIcon::HOUSE),
            0x2D => Some(ItemIcon::PLANT),
            0x2F => Some(ItemIcon::MOCHA),
            0x30 => Some(ItemIcon::POT),
            0x31 => Some(ItemIcon::BOOMERANG),
            0x32 => Some(ItemIcon::COATING),
            0x33 => Some(ItemIcon::EMPTY_BOTTLE),
            0x34 => Some(ItemIcon::CARAPACE),
            0x4F => Some(ItemIcon::SWORD_CRYSTAL),
            0x50 => Some(ItemIcon::POTION),
            0x52 => Some(ItemIcon::FRUIT),
            0x56 => Some(ItemIcon::TOWER_W_SIGIL),
            0x5B => Some(ItemIcon::TOWER_A_SIGIL),
            0x5C => Some(ItemIcon::MANTLE),
            0x5D => Some(ItemIcon::ARMOR_SPHERE),
            _ => None,
        }
    }

    pub fn to_u8(self) -> u8 {
        self as u8
    }

    pub fn to_string(self) -> String {
        match self {
            ItemIcon::SMOKE => "Smoke".to_string(),
            ItemIcon::ORB => "Orb".to_string(),
            ItemIcon::BOMB => "Bomb".to_string(),
            ItemIcon::MEAT => "Meat".to_string(),
            ItemIcon::FISH_BAIT => "Fish Bait".to_string(),
            ItemIcon::FISH => "Fish".to_string(),
            ItemIcon::BOX => "Box".to_string(),
            ItemIcon::WHETSTONE => "Whetstone".to_string(),
            ItemIcon::DUNG => "Dung".to_string(),
            ItemIcon::MONSTER => "Monster".to_string(),
            ItemIcon::BONES => "Bones".to_string(),
            ItemIcon::BINOCULARS => "Binoculars".to_string(),
            ItemIcon::MUSHROOM => "Mushroom".to_string(),
            ItemIcon::BUGNET => "Bugnet".to_string(),
            ItemIcon::PELT => "Pelt".to_string(),
            ItemIcon::LEAF => "Leaf".to_string(),
            ItemIcon::PICKAXE => "Pickaxe".to_string(),
            ItemIcon::BARREL => "Barrel".to_string(),
            ItemIcon::SEED => "Seed".to_string(),
            ItemIcon::BBQ_SPIT => "BBQ Spit".to_string(),
            ItemIcon::INSECT => "Insect".to_string(),
            ItemIcon::TRAP => "Trap".to_string(),
            ItemIcon::NET => "Net".to_string(),
            ItemIcon::SCALE => "Scale".to_string(),
            ItemIcon::DRINK => "Drink".to_string(),
            ItemIcon::EGG => "Egg".to_string(),
            ItemIcon::AMMO => "Ammo".to_string(),
            ItemIcon::STONE => "Stone".to_string(),
            ItemIcon::HUSK => "Husk".to_string(),
            ItemIcon::MAP => "Map".to_string(),
            ItemIcon::FLUTE => "Flute".to_string(),
            ItemIcon::FANG => "Fang".to_string(),
            ItemIcon::GRID => "Grid".to_string(),
            ItemIcon::QUESTION_MARK => "Question Mark".to_string(),
            ItemIcon::COIN => "Coin".to_string(),
            ItemIcon::SAC => "Sac".to_string(),
            ItemIcon::BOOK => "Book".to_string(),
            ItemIcon::TICKET => "Ticket".to_string(),
            ItemIcon::KNIFE => "Knife".to_string(),
            ItemIcon::MUSIC_SHEET => "Music Sheet".to_string(),
            ItemIcon::JEWEL => "Jewel".to_string(),
            ItemIcon::HOUSE => "House".to_string(),
            ItemIcon::PLANT => "Plant".to_string(),
            ItemIcon::MOCHA => "Mocha".to_string(),
            ItemIcon::POT => "Pot".to_string(),
            ItemIcon::BOOMERANG => "Boomerang".to_string(),
            ItemIcon::COATING => "Coating".to_string(),
            ItemIcon::EMPTY_BOTTLE => "Empty Bottle".to_string(),
            ItemIcon::CARAPACE => "Carapace".to_string(),
            ItemIcon::SWORD_CRYSTAL => "Sword Crystal".to_string(),
            ItemIcon::POTION => "Potion".to_string(),
            ItemIcon::FRUIT => "Fruit".to_string(),
            ItemIcon::TOWER_W_SIGIL => "Tower W Sigil".to_string(),
            ItemIcon::TOWER_A_SIGIL => "Tower A Sigil".to_string(),
            ItemIcon::MANTLE => "Mantle".to_string(),
            ItemIcon::ARMOR_SPHERE => "Armor Sphere".to_string(),
        }
    }
}

/// List of all item icons for UI selection
pub const ITEM_ICON_LIST: &[(u8, &str)] = &[
    (0x00, "Smoke"),
    (0x01, "Orb"),
    (0x02, "Bomb"),
    (0x03, "Meat"),
    (0x04, "Fish Bait"),
    (0x05, "Fish"),
    (0x06, "Box"),
    (0x07, "Whetstone"),
    (0x08, "Dung"),
    (0x09, "Monster"),
    (0x0A, "Bones"),
    (0x0B, "Binoculars"),
    (0x0C, "Mushroom"),
    (0x0D, "Bugnet"),
    (0x0E, "Pelt"),
    (0x0F, "Leaf"),
    (0x10, "Pickaxe"),
    (0x11, "Barrel"),
    (0x12, "Seed"),
    (0x13, "BBQ Spit"),
    (0x14, "Insect"),
    (0x15, "Trap"),
    (0x16, "Net"),
    (0x17, "Scale"),
    (0x18, "Drink"),
    (0x19, "Egg"),
    (0x1A, "Ammo"),
    (0x1B, "Stone"),
    (0x1C, "Husk"),
    (0x1D, "Map"),
    (0x1E, "Flute"),
    (0x1F, "Fang"),
    (0x20, "Grid"),
    (0x21, "Question Mark"),
    (0x22, "Coin"),
    (0x23, "Sac"),
    (0x24, "Book"),
    (0x25, "Ticket"),
    (0x26, "Knife"),
    (0x29, "Music Sheet"),
    (0x2B, "Jewel"),
    (0x2C, "House"),
    (0x2D, "Plant"),
    (0x2F, "Mocha"),
    (0x30, "Pot"),
    (0x31, "Boomerang"),
    (0x32, "Coating"),
    (0x33, "Empty Bottle"),
    (0x34, "Carapace"),
    (0x4F, "Sword Crystal"),
    (0x50, "Potion"),
    (0x52, "Fruit"),
    (0x56, "Tower W Sigil"),
    (0x5B, "Tower A Sigil"),
    (0x5C, "Mantle"),
    (0x5D, "Armor Sphere"),
];

/// Get icon name by value
pub fn icon_name(value: u8) -> String {
    if let Some(icon) = ItemIcon::from_u8(value) {
        icon.to_string()
    } else {
        format!("Unknown (0x{:02X})", value)
    }
}

/// Equipment type helper function based on pattern
pub fn equip_type_name(value: u16) -> String {
    match value {
        0x00 => "Normal Cuff".to_string(),
        0x01 => "Premium Cuff".to_string(),
        0x02 => "Cat Deco".to_string(),
        0x03 => "Cat Deco2".to_string(),
        0x04 => "Tower Deco".to_string(),
        0x06 => "Sigil".to_string(),
        0x07 => "Sigil2".to_string(),
        0x08 => "Z Cuff".to_string(),
        0x09 => "Premium Z Cuff".to_string(),
        0x0A => "Sigil3".to_string(),
        0x0B => "Hidden Cuff".to_string(),
        _ => format!("Unknown (0x{:04X})", value),
    }
}

/// Item type helper function
pub fn item_type_name(value: u16) -> String {
    match value {
        0x04 => "Consumable".to_string(),
        0x05 => "Placeable".to_string(),
        _ => format!("Unknown (0x{:04X})", value),
    }
}

/// Icon color helper function
pub fn icon_color_name(value: u8) -> String {
    match value {
        0x00 => "White".to_string(),
        0x01 => "Red".to_string(),
        0x02 => "Green".to_string(),
        0x03 => "Blue".to_string(),
        0x04 => "Yellow".to_string(),
        0x05 => "Purple".to_string(),
        0x06 => "Light Blue".to_string(),
        0x08 => "Pink".to_string(),
        0x0A => "Gray".to_string(),
        _ => format!("Unknown (0x{:02X})", value),
    }
}
