/// Map ID to name mapping for MHFJMP
pub fn get_map_name(map_id: u16) -> &'static str {
    match map_id {
        1 => "Jungle Night Basecamp",
        2 => "Jungle Night Area 1",
        3 => "Jungle Night Area 2",
        4 => "Jungle Night Area 3",
        5 => "Jungle Night Area 4",
        6 => "Snowy Mountains Day Secret Area",
        7 => "Desert Day Secret Area",
        8 => "Volcano Day Secret Area",
        9 => "Swamp Day Secret Area",
        10 => "Siege Fortress Day",
        11 => "Siege Fortress Day",
        12 => "Siege Fortress Day",
        13 => "Arena with Moat Day Area 1",
        14 => "Siege Fortress Day",
        15 => "Snowy Mountains Night Secret Area",
        16 => "Swamp Night Basecamp",
        17 => "Arena with Moat Night Area 1",
        18 => "Jungle Night Area 5",
        19 => "Jungle Night Area 9",
        20 => "Castle Schrade Base Camp/Area 1",
        21 => "Forest and Hills Day Basecamp",
        22 => "Jungle Night Area 8",
        23 => "Jungle Night Area 7",
        24 => "Desert Night Secret Area",
        25 => "Castle Schrade Area 2",
        26 => "Jungle Night Area 6",
        27 => "Volcano Night Secret Area",
        28 => "Siege Fortress Day",
        29 => "Swamp Night Secret Area",
        30 => "Siege Fortress Day",
        31 => "Siege Fortress Day",
        32 => "Forest and Hills Day Area 6",
        33 => "Forest and Hills Day Area 3",
        34 => "Forest and Hills Day Area 10",
        35 => "Forest and Hills Day Area 8",
        36 => "Forest and Hills Day Area 9",
        37 => "Forest and Hills Day Area 4",
        38 => "Forest and Hills Day Area 2",
        39 => "Forest and Hills Day Area 1",
        40 => "Forest and Hills Day Area 5",
        41 => "Forest and Hills Day Area 7",
        42 => "Forest and Hills Day Area 11",
        43 => "Forest and Hills Day Area 12",
        44 => "Duplicate of Swamp Night Area 1",
        45 => "Desert Camp Night",
        46 => "Arena with Moat Night Basecamp",
        47 => "Desert Night Area 2",
        48 => "Desert Night Area 7",
        49 => "Desert Night Area 3",
        50 => "Desert Night Area 6",
        51 => "Desert Night Area 5",
        52 => "Desert Night Area 1",
        53 => "Desert Night Area 4",
        54 => "Desert Night Area 8",
        55 => "Desert Night Area 9",
        56 => "Desert Night Area 10",
        57 => "Arena with Pillar Night Area 1",
        58 => "Volcano Night Basecamp",
        59 => "Volcano Night Area 4",
        60 => "Volcano Night Area 5",
        61 => "Volcano Night Area 1",
        62 => "Volcano Night Area 2",
        63 => "Volcano Night Area 3",
        64 => "Volcano Night Area 7",
        65 => "Volcano Night Area 6",
        66 => "Arena with Pillar (Cat Arena) Night Area 1",
        67 => "Swamp Night Area 2",
        68 => "Swamp Night Area 3",
        69 => "Swamp Night Area 9",
        70 => "Swamp Night Area 8",
        71 => "Swamp Night Area 6",
        72 => "Swamp Night Area 5",
        73 => "Swamp Night Area 7",
        74 => "Volcano Night Secret Area",
        75 => "Swamp Night Area 4",
        76 => "Not Used",
        77 => "Not Used",
        78 => "Not Used",
        79 => "Not Used",
        80 => "Not Used",
        81 => "Not Used",
        82 => "Not Used",
        83 => "Tower 3 Area 8",
        84 => "Tower 3 Area 9",
        85 => "Not Used",
        86 => "Kokoto Village House",
        87 => "Kokoto Village",
        88 => "Crimson Battleground",
        89 => "Arena with Pillar (Cat Arena) Day Base Camp",
        90 => "Arena with Ledge Day",
        91 => "Arena with Pillar (Cat Arena) Day Area 1",
        92 => "Snowy Mountains Day Area 4",
        93 => "Snowy Mountains Day Area 5",
        94 => "Snowy Mountains Day Area 3",
        95 => "Snowy Mountains Day Area 2",
        96 => "Snowy Mountains Day Area 7",
        97 => "Snowy Mountains Day Area 8",
        98 => "Snowy Mountains Day Basecamp",
        99 => "Snowy Mountains Day Area 1",
        100 => "Snowy Mountains Day Area 6",
        101 => "Snowy Mountains Night Area 4",
        102 => "Snowy Mountains Night Area 5",
        103 => "Snowy Mountains Night Area 3",
        104 => "Snowy Mountains Night Area 2",
        105 => "Snowy Mountains Night Area 7",
        106 => "Snowy Mountains Night Area 8",
        107 => "Snowy Mountains Night Base Camp",
        108 => "Snowy Mountains Night Area 1",
        109 => "Snowy Mountains Night Area 6",
        110 => "Jungle Day Basecamp",
        111 => "Jungle Day Area 10",
        112 => "Jungle Day Area 2",
        113 => "Jungle Day Area 3",
        114 => "Jungle Day Area 4",
        115 => "Jungle Day Area 5",
        116 => "Jungle Day Area 9",
        117 => "Jungle Day Area 8",
        118 => "Jungle Day Area 7",
        119 => "Jungle Day Area 6",
        120 => "Jungle Day Area 10",
        121 => "Tower 3 Camp",
        122 => "Tower 3 Area 1",
        123 => "Tower 3 Area 2",
        124 => "Tower 3 Area 10",
        125 => "Tower 3 Area 6 (7 in tower 1)",
        126 => "Tower 1 Area 8",
        127 => "Tower 3 Area 7 (6 in tower 1)",
        128 => "Tower 3 Area 5 (4 in tower 1)",
        129 => "Tower 3 Area 4 (5 in tower 1)",
        130 => "Tower 3 Area 3",
        131 => "Dundorma Town Square",
        132 => "Dundorma Main Area",
        133 => "Dundorma Smithy",
        134 => "Dundorma Public Tavern",
        135 => "Dundorma Arena",
        136 => "Dundorma Grand Priest",
        137 => "Jumbo Village",
        138 => "Tower 2",
        139 => "Tower 1 Area 9/Tower with Nesthole",
        140 => "Desert Day Basecamp",
        141 => "Desert Day Area 2",
        142 => "Desert Day Area 7",
        143 => "Desert Day Area 3",
        144 => "Desert Day Area 6",
        145 => "Desert Day Area 5",
        146 => "Desert Day Area 1",
        147 => "Desert Day Area 4",
        148 => "Desert Day Area 8",
        149 => "Desert Day Area 9",
        150 => "Desert Day Area 10",
        151 => "Swamp Day Basecamp",
        152 => "Swamp Day Area 1",
        153 => "Swamp Day Area 2",
        154 => "Swamp Day Area 3",
        155 => "Swamp Day Area 9",
        156 => "Swamp Day Area 8",
        157 => "Swamp Day Area 6",
        158 => "Swamp Day Area 5",
        159 => "Swamp Day Area 7",
        160 => "Swamp Day Area 4",
        161 => "Volcano Day Basecamp",
        162 => "Volcano Day Area 4",
        163 => "Volcano Day Area 5",
        164 => "Volcano Day Area 1",
        165 => "Volcano Day Area 2",
        166 => "Volcano Day Area 3",
        167 => "Volcano Day Area 7",
        168 => "Volcano Day Area 6",
        169 => "Volcano Day Area 8",
        170 => "Jumbo Mine Lv1",
        171 => "Jumbo Mine Lv2",
        172 => "Jumbo Mine Lv3",
        173 => "My House Lv1",
        174 => "My House Lv2",
        175 => "My House Lv3",
        176 => "Dundorma Fort 03",
        177 => "Dundorma Fort 02",
        178 => "Dundorma Fort 01",
        179 => "Dundorma Fort BC",
        180 => "Dundorma Fort 03",
        181 => "Dundorma Fort 02",
        182 => "Dundorma Fort 01",
        183 => "Dundorma Fort BC",
        184 => "Forest and hill Night base camp",
        185 => "Forest and hill Night Area 6",
        186 => "Forest and hill Night Area 3",
        187 => "Forest and hill Night Area 10",
        188 => "Forest and hill Night Area 8",
        189 => "Forest and HIll Night 9",
        190 => "Forest and hill Night Area 4",
        191 => "Forest and hill Night Area 2",
        192 => "Forest and hill Night Area 1",
        193 => "Forest and hill Night Area 5",
        194 => "Forest and Hills Night Area 7",
        195 => "Forest and Hills Night Area 11",
        196 => "Forest and Hills Night Area 12",
        197 => "Akantor Battleground",
        198 => "Not used",
        199 => "Not used",
        200 => "Mezeporta",
        201 => "Hairdresser",
        202 => "Guild Hall Lv1",
        203 => "Guild Hall Lv2",
        204 => "Guild Hall Max",
        205 => "Pugi Farm",
        206 => "Rookie Camp",
        207 => "Rookie Camp Smithy",
        208 => "Not used",
        209 => "Not used",
        210 => "Private Bar",
        211 => "Rasta Bar",
        212 => "Jungle Pioneer Secret 01",
        213 => "Jungle Pioneer Secret 02",
        214 => "Desert Pioneer Secret 01",
        215 => "Desert Pioneer Secret 02",
        216 => "Volcano Pioneer Secret 01",
        217 => "Volcano Pioneer Secret 02",
        218 => "Snowy Mountain Pioneer Secret 01",
        219 => "Snowy Mountain Pioneer Secret 02",
        220 => "Volcano Day Area 9",
        221 => "Volcano Night Area 9",
        222 => "Volcano Day Area 10",
        223 => "Volcano Night Area 10",
        224 => "Great Forest Day Base Camp",
        225 => "Great Forest Night Base Camp",
        226 => "Great Forest Day Area 1",
        227 => "Great Forest Night Area 1",
        228 => "Great Forest Day Area 2",
        229 => "Great Forest Night Area 2",
        230 => "Great Forest Day Area 3",
        231 => "Great Forest Night Area 3",
        232 => "Great Forest Day Area 4",
        233 => "Great Forest Night Area 4",
        234 => "Great Forest Day Area 5",
        235 => "Great Forest Night Area 5",
        236 => "Great Forest Day Area 6",
        237 => "Great Forest Night Area 6",
        238 => "Great Forest Day Area 7",
        239 => "Great Forest Night Area 7",
        240 => "Great Forest Day Area 8",
        241 => "Great Forest Night Area 8",
        242 => "Unused Version of the Top of G.Forest (Day?)",
        243 => "Unused Version of the Top of G.Forest (Night?)",
        244 => "Code Claiming Room",
        245 => "Top of Great Forest Day Camp",
        246 => "Top of Great Forest Day Area 1",
        247 => "Highlands Base Day Camp",
        248 => "Highlands Night Basecamp",
        249 => "Highlands Day Area 1",
        250 => "Highlands Night Area 1",
        251 => "Highlands Day Area 2",
        252 => "Highlands Night Area 2",
        253 => "Highlands Day Area 3",
        254 => "Highlands Night Area 3",
        255 => "Highlands Day Area 4",
        256 => "Caravan Changing Area (Unused? Night/Day?)",
        257 => "Blacksmith",
        258 => "Caravan Blimp Basecamp",
        259 => "Caravan Blimp Basecamp",
        260 => "Caravan Area",
        261 => "Caravan Changing Area",
        262 => "Caravan Guest House",
        263 => "Caravan Guest House Second Floor",
        264 => "Gallery",
        265 => "Gook Farm",
        266 => "Not used",
        267 => "Not used",
        268 => "Not used",
        269 => "Not used",
        270 => "Not used",
        271 => "Not used",
        272 => "Interception Base, Fortress Day Base Camp",
        273 => "Fortress Night Base Camp",
        274 => "Interception Base, Fortress Day Area 1",
        275 => "Fortress Night Area 1",
        276 => "Fortress Day Area 2",
        277 => "Fortress Night Area 2",
        278 => "Interception Base, Fortress Day Area 3",
        279 => "Fortress Night Area 3",
        280 => "Arena with Moat Day Base Camp",
        281 => "Arena with Moat Day Base Camp (Dupe?)",
        282 => "Cities Map",
        283 => "Halk Area",
        284 => "Not used",
        285 => "Not used",
        286 => "PvP Room",
        287 => "Not used",
        288 => "Gorge Day Basecamp",
        289 => "Gorge Night Basecamp",
        290 => "Gorge Day Basecamp",
        291 => "Gorge Night Area 1",
        292 => "Gorge Day Area 1",
        293 => "Gorge Night Area 2",
        294 => "Gorge Day Area 2",
        295 => "Gorge Night Area 3",
        296 => "Gorge Day Area 3",
        297 => "Gorge Night Area 4",
        298 => "Gorge Day Area 4",
        299 => "Gorge Night Area 5",
        300 => "Gorge Day Area 5",
        301 => "Gorge Night Area 6",
        302 => "Highlands Night Area 4",
        303 => "Highlands Day Area 5",
        304 => "Highlands Night Area 5",
        305 => "Highlands Day Area 6",
        306 => "Highlands Night Area 6",
        307 => "Highlands Day Area 7",
        308 => "Highlands Night Area 7",
        309 => "Solitude Island",
        310 => "Campaign Tent",
        311 => "Raviente Balloon",
        312 => "Raviente Balloon",
        313 => "Solitude Island",
        314 => "Solitude Isle 1",
        315 => "Solitude Island",
        316 => "Solitude Island",
        317 => "Solitude Isle 2",
        318 => "Solitude Island",
        319 => "Solitude Island",
        320 => "Solitude Isle 3",
        321 => "Solitude Island",
        322 => "Tidal Island Day Basecamp",
        323 => "Tidal Island Day Area 1",
        324 => "Tidal Island Day Area 2",
        325 => "Tidal Island Day Area 3",
        326 => "Tidal Island Day",
        327 => "Tidal Island Day",
        328 => "Tidal Island Day",
        329 => "Tidal Island Day",
        330 => "Tidal Island Base Camp (Night)",
        331 => "Tidal Island Area 1 (Night)",
        332 => "Tidal Island Area 2 (Night)",
        333 => "Tidal Island Area 3 (Night)",
        334 => "Tidal Island Day Area 4",
        335 => "Tidal Island Day Area 5",
        336 => "Tidal Island Day",
        337 => "Tidal Island (orangish area 5)",
        338 => "Tidal Island Area 4 (Night)",
        339 => "Tidal Island Area 5 (Night)",
        340 => "SR Room",
        341 => "SR Room",
        342 => "Large Airship BC Day",
        343 => "Large Airship Deck Day",
        344 => "Large Airship Crashed",
        345 => "Polar Sea Basecamp Day",
        346 => "Polar Sea Night",
        347 => "Polar Sea Day Area 1",
        348 => "Polar Sea Night Area 1",
        349 => "Polar Sea Day Area 2",
        350 => "Polar Sea Night Area 2",
        351 => "Polar Sea Day Area 3",
        352 => "Polar Sea Night Area 3",
        353 => "Polar Sea Day Area 4",
        354 => "Polar Sea Night Area 4",
        355 => "Polar Sea Day Area 5",
        356 => "Polar Sea Night Area 5",
        357 => "Polar Sea Day Area 6",
        358 => "Polar Sea Night Area 6",
        359 => "World's End BC",
        360 => "World's End Area 1",
        361 => "Flower Field Day Base Camp",
        362 => "Flower Field Night Base Camp",
        363 => "Flower Field Day Area 1",
        364 => "Flower Field Night Area 1",
        365 => "Flower Field Day Area 2",
        366 => "Flower Field Night Area 2",
        367 => "Flower Field Day Area 3",
        368 => "Flower Field Night Area 3",
        369 => "Flower Field Day Area 4",
        370 => "Flower Field Night Area 4",
        371 => "Flower Field Day Area 5",
        372 => "Flower Field Night Area 5",
        373 => "Top of Tower",
        374 => "Deep Crater Area 1",
        375 => "Bamboo Entrance Day",
        376 => "Bamboo Entrance Night",
        377 => "Bamboo Forest Day Area 1",
        378 => "Bamboo Forest Night Area 1",
        379 => "Diva Hall",
        380 => "Battlefield Entrance, Deep Crater BC",
        381 => "Not used",
        382 => "Not used",
        383 => "Not used",
        384 => "Not used",
        385 => "Not used",
        386 => "Not used",
        387 => "Not used",
        388 => "Not used",
        389 => "Not used",
        390 => "Tower 01",
        391 => "Tower Airship",
        392 => "Tower Entrance",
        393 => "Tower 02",
        394 => "Urgent Tower",
        395 => "ABSENT",
        396 => "Battlefield Varusa",
        397 => "Mezeporta Dupe (nonHD)",
        398 => "Dure Arena",
        399 => "Dure Doorway",
        400 => "White Lake Day Base Camp",
        401 => "White Lake Night Base Camp",
        402 => "White Lake Day Area 1",
        403 => "White Lake Night Area 1",
        404 => "White Lake Day Area 2",
        405 => "White Lake Night Area 2",
        406 => "White Lake Day Area 3",
        407 => "White Lake Night Area 3",
        408 => "White Lake Day Area 4",
        409 => "White Lake Night Area 4",
        410 => "White Lake Day Area 5",
        411 => "White Lake Night Area 5",
        412 => "White Lake Day Area 6",
        413 => "White Lake Night Area 6",
        414 => "Duremudira Door",
        415 => "Urgent Tower",
        416 => "4th Dist Tower",
        417 => "Berserk Ravi BC Slay 1",
        418 => "Berserk Combat 01",
        419 => "Berserk Combat 02",
        420 => "Berserk Combat 03",
        421 => "Berserk Combat 04",
        422 => "Berserk Combat 05",
        423 => "Painted Falls Day Base Camp",
        424 => "Painted Falls Night",
        425 => "Painted Falls Day Area 1",
        426 => "Painted Falls Night",
        427 => "Painted Falls Day Area 2",
        428 => "Painted Falls Night",
        429 => "Painted Falls Day Area 3",
        430 => "Painted Falls Night",
        431 => "Painted Falls Day Area 4",
        432 => "Painted Falls Night",
        433 => "Painted Falls Day Area 5",
        434 => "Painted Falls Night",
        435 => "Painted Falls Day Area 6",
        436 => "Painted Falls Night",
        437 => "Berserk Ravi BC",
        438 => "Guanz Arena 01",
        439 => "Guanz Arena 02",
        440 => "Berserk Support 01",
        441 => "Berserk Support 02",
        442 => "Berserk Support 03",
        443 => "Berserk Support 04",
        444 => "Berserk Support 05",
        445 => "Diva Hall",
        446 => "Amatsu Arena 1",
        447 => "Amatsu Arena 2",
        448 => "Shagaru Arena 1",
        449 => "Shagaru Arena 2",
        450 => "Interception/Fortress Camp Duplicate (noHD)",
        451 => "Interception/Fortress Camp Duplicate (noHD)",
        452 => "Interception/Fortress Area 1 (one with bunch of bridges) Duplicate (noHD)",
        453 => "Interception/Fortress Area 1 (one with bunch of bridges) Duplicate (noHD)",
        454 => "Interception/Fortress Area 2 Duplicate (noHD)",
        455 => "Interception/Fortress Area 2 Duplicate (noHD)",
        456 => "Interception/Fortress Area 3 (Main Area) Duplicate (noHD)",
        457 => "Interception/Fortress Area 3 (Main Area) Duplicate (noHD)",
        458 => "Hunter's Road 1 Area 1",
        459 => "Hunter's Road 2 Base Camp",
        460 => "Historic 1",
        461 => "Historic 2",
        462 => "MezFes Entrance",
        463 => "Partnyaa Raceway",
        464 => "Shooting Game",
        465 => "MezFes Minigame",
        466 => "MezFes Minigame",
        467 => "MezFes Minigame",
        468 => "Can be used as a black void arena",
        469 => "Minigame Room",
        _ => "Unknown Map",
    }
}

/// List of all map IDs and names
pub const MAP_LIST: &[(u16, &str)] = &[
    (1, "Jungle Night Basecamp"),
    (2, "Jungle Night Area 1"),
    (3, "Jungle Night Area 2"),
    (4, "Jungle Night Area 3"),
    (5, "Jungle Night Area 4"),
    (6, "Snowy Mountains Day Secret Area"),
    (7, "Desert Day Secret Area"),
    (8, "Volcano Day Secret Area"),
    (9, "Swamp Day Secret Area"),
    (10, "Siege Fortress Day"),
    (11, "Siege Fortress Day"),
    (12, "Siege Fortress Day"),
    (13, "Arena with Moat Day Area 1"),
    (14, "Siege Fortress Day"),
    (15, "Snowy Mountains Night Secret Area"),
    (16, "Swamp Night Basecamp"),
    (17, "Arena with Moat Night Area 1"),
    (18, "Jungle Night Area 5"),
    (19, "Jungle Night Area 9"),
    (20, "Castle Schrade Base Camp/Area 1"),
    (21, "Forest and Hills Day Basecamp"),
    (22, "Jungle Night Area 8"),
    (23, "Jungle Night Area 7"),
    (24, "Desert Night Secret Area"),
    (25, "Castle Schrade Area 2"),
    (26, "Jungle Night Area 6"),
    (27, "Volcano Night Secret Area"),
    (28, "Siege Fortress Day"),
    (29, "Swamp Night Secret Area"),
    (30, "Siege Fortress Day"),
    (31, "Siege Fortress Day"),
    (32, "Forest and Hills Day Area 6"),
    (33, "Forest and Hills Day Area 3"),
    (34, "Forest and Hills Day Area 10"),
    (35, "Forest and Hills Day Area 8"),
    (36, "Forest and Hills Day Area 9"),
    (37, "Forest and Hills Day Area 4"),
    (38, "Forest and Hills Day Area 2"),
    (39, "Forest and Hills Day Area 1"),
    (40, "Forest and Hills Day Area 5"),
    (41, "Forest and Hills Day Area 7"),
    (42, "Forest and Hills Day Area 11"),
    (43, "Forest and Hills Day Area 12"),
    (44, "Duplicate of Swamp Night Area 1"),
    (45, "Desert Camp Night"),
    (46, "Arena with Moat Night Basecamp"),
    (47, "Desert Night Area 2"),
    (48, "Desert Night Area 7"),
    (49, "Desert Night Area 3"),
    (50, "Desert Night Area 6"),
    (51, "Desert Night Area 5"),
    (52, "Desert Night Area 1"),
    (53, "Desert Night Area 4"),
    (54, "Desert Night Area 8"),
    (55, "Desert Night Area 9"),
    (56, "Desert Night Area 10"),
    (57, "Arena with Pillar Night Area 1"),
    (58, "Volcano Night Basecamp"),
    (59, "Volcano Night Area 4"),
    (60, "Volcano Night Area 5"),
    (61, "Volcano Night Area 1"),
    (62, "Volcano Night Area 2"),
    (63, "Volcano Night Area 3"),
    (64, "Volcano Night Area 7"),
    (65, "Volcano Night Area 6"),
    (66, "Arena with Pillar (Cat Arena) Night Area 1"),
    (67, "Swamp Night Area 2"),
    (68, "Swamp Night Area 3"),
    (69, "Swamp Night Area 9"),
    (70, "Swamp Night Area 8"),
    (71, "Swamp Night Area 6"),
    (72, "Swamp Night Area 5"),
    (73, "Swamp Night Area 7"),
    (74, "Volcano Night Secret Area"),
    (75, "Swamp Night Area 4"),
    (76, "Not Used"),
    (77, "Not Used"),
    (78, "Not Used"),
    (79, "Not Used"),
    (80, "Not Used"),
    (81, "Not Used"),
    (82, "Not Used"),
    (83, "Tower 3 Area 8"),
    (84, "Tower 3 Area 9"),
    (85, "Not Used"),
    (86, "Kokoto Village House"),
    (87, "Kokoto Village"),
    (88, "Crimson Battleground"),
    (89, "Arena with Pillar (Cat Arena) Day Base Camp"),
    (90, "Arena with Ledge Day"),
    (91, "Arena with Pillar (Cat Arena) Day Area 1"),
    (92, "Snowy Mountains Day Area 4"),
    (93, "Snowy Mountains Day Area 5"),
    (94, "Snowy Mountains Day Area 3"),
    (95, "Snowy Mountains Day Area 2"),
    (96, "Snowy Mountains Day Area 7"),
    (97, "Snowy Mountains Day Area 8"),
    (98, "Snowy Mountains Day Basecamp"),
    (99, "Snowy Mountains Day Area 1"),
    (100, "Snowy Mountains Day Area 6"),
    (101, "Snowy Mountains Night Area 4"),
    (102, "Snowy Mountains Night Area 5"),
    (103, "Snowy Mountains Night Area 3"),
    (104, "Snowy Mountains Night Area 2"),
    (105, "Snowy Mountains Night Area 7"),
    (106, "Snowy Mountains Night Area 8"),
    (107, "Snowy Mountains Night Base Camp"),
    (108, "Snowy Mountains Night Area 1"),
    (109, "Snowy Mountains Night Area 6"),
    (110, "Jungle Day Basecamp"),
    (111, "Jungle Day Area 10"),
    (112, "Jungle Day Area 2"),
    (113, "Jungle Day Area 3"),
    (114, "Jungle Day Area 4"),
    (115, "Jungle Day Area 5"),
    (116, "Jungle Day Area 9"),
    (117, "Jungle Day Area 8"),
    (118, "Jungle Day Area 7"),
    (119, "Jungle Day Area 6"),
    (120, "Jungle Day Area 10"),
    (121, "Tower 3 Camp"),
    (122, "Tower 3 Area 1"),
    (123, "Tower 3 Area 2"),
    (124, "Tower 3 Area 10"),
    (125, "Tower 3 Area 6 (7 in tower 1)"),
    (126, "Tower 1 Area 8"),
    (127, "Tower 3 Area 7 (6 in tower 1)"),
    (128, "Tower 3 Area 5 (4 in tower 1)"),
    (129, "Tower 3 Area 4 (5 in tower 1)"),
    (130, "Tower 3 Area 3"),
    (131, "Dundorma Town Square"),
    (132, "Dundorma Main Area"),
    (133, "Dundorma Smithy"),
    (134, "Dundorma Public Tavern"),
    (135, "Dundorma Arena"),
    (136, "Dundorma Grand Priest"),
    (137, "Jumbo Village"),
    (138, "Tower 2"),
    (139, "Tower 1 Area 9/Tower with Nesthole"),
    (140, "Desert Day Basecamp"),
    (141, "Desert Day Area 2"),
    (142, "Desert Day Area 7"),
    (143, "Desert Day Area 3"),
    (144, "Desert Day Area 6"),
    (145, "Desert Day Area 5"),
    (146, "Desert Day Area 1"),
    (147, "Desert Day Area 4"),
    (148, "Desert Day Area 8"),
    (149, "Desert Day Area 9"),
    (150, "Desert Day Area 10"),
    (151, "Swamp Day Basecamp"),
    (152, "Swamp Day Area 1"),
    (153, "Swamp Day Area 2"),
    (154, "Swamp Day Area 3"),
    (155, "Swamp Day Area 9"),
    (156, "Swamp Day Area 8"),
    (157, "Swamp Day Area 6"),
    (158, "Swamp Day Area 5"),
    (159, "Swamp Day Area 7"),
    (160, "Swamp Day Area 4"),
    (161, "Volcano Day Basecamp"),
    (162, "Volcano Day Area 4"),
    (163, "Volcano Day Area 5"),
    (164, "Volcano Day Area 1"),
    (165, "Volcano Day Area 2"),
    (166, "Volcano Day Area 3"),
    (167, "Volcano Day Area 7"),
    (168, "Volcano Day Area 6"),
    (169, "Volcano Day Area 8"),
    (170, "Jumbo Mine Lv1"),
    (171, "Jumbo Mine Lv2"),
    (172, "Jumbo Mine Lv3"),
    (173, "My House Lv1"),
    (174, "My House Lv2"),
    (175, "My House Lv3"),
    (176, "Dundorma Fort 03"),
    (177, "Dundorma Fort 02"),
    (178, "Dundorma Fort 01"),
    (179, "Dundorma Fort BC"),
    (180, "Dundorma Fort 03"),
    (181, "Dundorma Fort 02"),
    (182, "Dundorma Fort 01"),
    (183, "Dundorma Fort BC"),
    (184, "Forest and hill Night base camp"),
    (185, "Forest and hill Night Area 6"),
    (186, "Forest and hill Night Area 3"),
    (187, "Forest and hill Night Area 10"),
    (188, "Forest and hill Night Area 8"),
    (189, "Forest and HIll Night 9"),
    (190, "Forest and hill Night Area 4"),
    (191, "Forest and hill Night Area 2"),
    (192, "Forest and hill Night Area 1"),
    (193, "Forest and hill Night Area 5"),
    (194, "Forest and Hills Night Area 7"),
    (195, "Forest and Hills Night Area 11"),
    (196, "Forest and Hills Night Area 12"),
    (197, "Akantor Battleground"),
    (198, "Not used"),
    (199, "Not used"),
    (200, "Mezeporta"),
    (201, "Hairdresser"),
    (202, "Guild Hall Lv1"),
    (203, "Guild Hall Lv2"),
    (204, "Guild Hall Max"),
    (205, "Pugi Farm"),
    (206, "Rookie Camp"),
    (207, "Rookie Camp Smithy"),
    (208, "Not used"),
    (209, "Not used"),
    (210, "Private Bar"),
    (211, "Rasta Bar"),
    (212, "Jungle Pioneer Secret 01"),
    (213, "Jungle Pioneer Secret 02"),
    (214, "Desert Pioneer Secret 01"),
    (215, "Desert Pioneer Secret 02"),
    (216, "Volcano Pioneer Secret 01"),
    (217, "Volcano Pioneer Secret 02"),
    (218, "Snowy Mountain Pioneer Secret 01"),
    (219, "Snowy Mountain Pioneer Secret 02"),
    (220, "Volcano Day Area 9"),
    (221, "Volcano Night Area 9"),
    (222, "Volcano Day Area 10"),
    (223, "Volcano Night Area 10"),
    (224, "Great Forest Day Base Camp"),
    (225, "Great Forest Night Base Camp"),
    (226, "Great Forest Day Area 1"),
    (227, "Great Forest Night Area 1"),
    (228, "Great Forest Day Area 2"),
    (229, "Great Forest Night Area 2"),
    (230, "Great Forest Day Area 3"),
    (231, "Great Forest Night Area 3"),
    (232, "Great Forest Day Area 4"),
    (233, "Great Forest Night Area 4"),
    (234, "Great Forest Day Area 5"),
    (235, "Great Forest Night Area 5"),
    (236, "Great Forest Day Area 6"),
    (237, "Great Forest Night Area 6"),
    (238, "Great Forest Day Area 7"),
    (239, "Great Forest Night Area 7"),
    (240, "Great Forest Day Area 8"),
    (241, "Great Forest Night Area 8"),
    (242, "Unused Version of the Top of G.Forest (Day?)"),
    (243, "Unused Version of the Top of G.Forest (Night?)"),
    (244, "Code Claiming Room"),
    (245, "Top of Great Forest Day Camp"),
    (246, "Top of Great Forest Day Area 1"),
    (247, "Highlands Base Day Camp"),
    (248, "Highlands Night Basecamp"),
    (249, "Highlands Day Area 1"),
    (250, "Highlands Night Area 1"),
    (251, "Highlands Day Area 2"),
    (252, "Highlands Night Area 2"),
    (253, "Highlands Day Area 3"),
    (254, "Highlands Night Area 3"),
    (255, "Highlands Day Area 4"),
    (256, "Caravan Changing Area (Unused? Night/Day?)"),
    (257, "Blacksmith"),
    (258, "Caravan Blimp Basecamp"),
    (259, "Caravan Blimp Basecamp"),
    (260, "Caravan Area"),
    (261, "Caravan Changing Area"),
    (262, "Caravan Guest House"),
    (263, "Caravan Guest House Second Floor"),
    (264, "Gallery"),
    (265, "Gook Farm"),
    (266, "Not used"),
    (267, "Not used"),
    (268, "Not used"),
    (269, "Not used"),
    (270, "Not used"),
    (271, "Not used"),
    (272, "Interception Base, Fortress Day Base Camp"),
    (273, "Fortress Night Base Camp"),
    (274, "Interception Base, Fortress Day Area 1"),
    (275, "Fortress Night Area 1"),
    (276, "Fortress Day Area 2"),
    (277, "Fortress Night Area 2"),
    (278, "Interception Base, Fortress Day Area 3"),
    (279, "Fortress Night Area 3"),
    (280, "Arena with Moat Day Base Camp"),
    (281, "Arena with Moat Day Base Camp (Dupe?)"),
    (282, "Cities Map"),
    (283, "Halk Area"),
    (284, "Not used"),
    (285, "Not used"),
    (286, "PvP Room"),
    (287, "Not used"),
    (288, "Gorge Day Basecamp"),
    (289, "Gorge Night Basecamp"),
    (290, "Gorge Day Basecamp"),
    (291, "Gorge Night Area 1"),
    (292, "Gorge Day Area 1"),
    (293, "Gorge Night Area 2"),
    (294, "Gorge Day Area 2"),
    (295, "Gorge Night Area 3"),
    (296, "Gorge Day Area 3"),
    (297, "Gorge Night Area 4"),
    (298, "Gorge Day Area 4"),
    (299, "Gorge Night Area 5"),
    (300, "Gorge Day Area 5"),
    (301, "Gorge Night Area 6"),
    (302, "Highlands Night Area 4"),
    (303, "Highlands Day Area 5"),
    (304, "Highlands Night Area 5"),
    (305, "Highlands Day Area 6"),
    (306, "Highlands Night Area 6"),
    (307, "Highlands Day Area 7"),
    (308, "Highlands Night Area 7"),
    (309, "Solitude Island"),
    (310, "Campaign Tent"),
    (311, "Raviente Balloon"),
    (312, "Raviente Balloon"),
    (313, "Solitude Island"),
    (314, "Solitude Isle 1"),
    (315, "Solitude Island"),
    (316, "Solitude Island"),
    (317, "Solitude Isle 2"),
    (318, "Solitude Island"),
    (319, "Solitude Island"),
    (320, "Solitude Isle 3"),
    (321, "Solitude Island"),
    (322, "Tidal Island Day Basecamp"),
    (323, "Tidal Island Day Area 1"),
    (324, "Tidal Island Day Area 2"),
    (325, "Tidal Island Day Area 3"),
    (326, "Tidal Island Day"),
    (327, "Tidal Island Day"),
    (328, "Tidal Island Day"),
    (329, "Tidal Island Day"),
    (330, "Tidal Island Base Camp (Night)"),
    (331, "Tidal Island Area 1 (Night)"),
    (332, "Tidal Island Area 2 (Night)"),
    (333, "Tidal Island Area 3 (Night)"),
    (334, "Tidal Island Day Area 4"),
    (335, "Tidal Island Day Area 5"),
    (336, "Tidal Island Day"),
    (337, "Tidal Island (orangish area 5)"),
    (338, "Tidal Island Area 4 (Night)"),
    (339, "Tidal Island Area 5 (Night)"),
    (340, "SR Room"),
    (341, "SR Room"),
    (342, "Large Airship BC Day"),
    (343, "Large Airship Deck Day"),
    (344, "Large Airship Crashed"),
    (345, "Polar Sea Basecamp Day"),
    (346, "Polar Sea Night"),
    (347, "Polar Sea Day Area 1"),
    (348, "Polar Sea Night Area 1"),
    (349, "Polar Sea Day Area 2"),
    (350, "Polar Sea Night Area 2"),
    (351, "Polar Sea Day Area 3"),
    (352, "Polar Sea Night Area 3"),
    (353, "Polar Sea Day Area 4"),
    (354, "Polar Sea Night Area 4"),
    (355, "Polar Sea Day Area 5"),
    (356, "Polar Sea Night Area 5"),
    (357, "Polar Sea Day Area 6"),
    (358, "Polar Sea Night Area 6"),
    (359, "World's End BC"),
    (360, "World's End Area 1"),
    (361, "Flower Field Day Base Camp"),
    (362, "Flower Field Night Base Camp"),
    (363, "Flower Field Day Area 1"),
    (364, "Flower Field Night Area 1"),
    (365, "Flower Field Day Area 2"),
    (366, "Flower Field Night Area 2"),
    (367, "Flower Field Day Area 3"),
    (368, "Flower Field Night Area 3"),
    (369, "Flower Field Day Area 4"),
    (370, "Flower Field Night Area 4"),
    (371, "Flower Field Day Area 5"),
    (372, "Flower Field Night Area 5"),
    (373, "Top of Tower"),
    (374, "Deep Crater Area 1"),
    (375, "Bamboo Entrance Day"),
    (376, "Bamboo Entrance Night"),
    (377, "Bamboo Forest Day Area 1"),
    (378, "Bamboo Forest Night Area 1"),
    (379, "Diva Hall"),
    (380, "Battlefield Entrance, Deep Crater BC"),
    (381, "Not used"),
    (382, "Not used"),
    (383, "Not used"),
    (384, "Not used"),
    (385, "Not used"),
    (386, "Not used"),
    (387, "Not used"),
    (388, "Not used"),
    (389, "Not used"),
    (390, "Tower 01"),
    (391, "Tower Airship"),
    (392, "Tower Entrance"),
    (393, "Tower 02"),
    (394, "Urgent Tower"),
    (395, "ABSENT"),
    (396, "Battlefield Varusa"),
    (397, "Mezeporta Dupe (nonHD)"),
    (398, "Dure Arena"),
    (399, "Dure Doorway"),
    (400, "White Lake Day Base Camp"),
    (401, "White Lake Night Base Camp"),
    (402, "White Lake Day Area 1"),
    (403, "White Lake Night Area 1"),
    (404, "White Lake Day Area 2"),
    (405, "White Lake Night Area 2"),
    (406, "White Lake Day Area 3"),
    (407, "White Lake Night Area 3"),
    (408, "White Lake Day Area 4"),
    (409, "White Lake Night Area 4"),
    (410, "White Lake Day Area 5"),
    (411, "White Lake Night Area 5"),
    (412, "White Lake Day Area 6"),
    (413, "White Lake Night Area 6"),
    (414, "Duremudira Door"),
    (415, "Urgent Tower"),
    (416, "4th Dist Tower"),
    (417, "Berserk Ravi BC Slay 1"),
    (418, "Berserk Combat 01"),
    (419, "Berserk Combat 02"),
    (420, "Berserk Combat 03"),
    (421, "Berserk Combat 04"),
    (422, "Berserk Combat 05"),
    (423, "Painted Falls Day Base Camp"),
    (424, "Painted Falls Night"),
    (425, "Painted Falls Day Area 1"),
    (426, "Painted Falls Night"),
    (427, "Painted Falls Day Area 2"),
    (428, "Painted Falls Night"),
    (429, "Painted Falls Day Area 3"),
    (430, "Painted Falls Night"),
    (431, "Painted Falls Day Area 4"),
    (432, "Painted Falls Night"),
    (433, "Painted Falls Day Area 5"),
    (434, "Painted Falls Night"),
    (435, "Painted Falls Day Area 6"),
    (436, "Painted Falls Night"),
    (437, "Berserk Ravi BC"),
    (438, "Guanz Arena 01"),
    (439, "Guanz Arena 02"),
    (440, "Berserk Support 01"),
    (441, "Berserk Support 02"),
    (442, "Berserk Support 03"),
    (443, "Berserk Support 04"),
    (444, "Berserk Support 05"),
    (445, "Diva Hall"),
    (446, "Amatsu Arena 1"),
    (447, "Amatsu Arena 2"),
    (448, "Shagaru Arena 1"),
    (449, "Shagaru Arena 2"),
    (450, "Interception/Fortress Camp Duplicate (noHD)"),
    (451, "Interception/Fortress Camp Duplicate (noHD)"),
    (452, "Interception/Fortress Area 1 (one with bunch of bridges) Duplicate (noHD)"),
    (453, "Interception/Fortress Area 1 (one with bunch of bridges) Duplicate (noHD)"),
    (454, "Interception/Fortress Area 2 Duplicate (noHD)"),
    (455, "Interception/Fortress Area 2 Duplicate (noHD)"),
    (456, "Interception/Fortress Area 3 (Main Area) Duplicate (noHD)"),
    (457, "Interception/Fortress Area 3 (Main Area) Duplicate (noHD)"),
    (458, "Hunter's Road 1 Area 1"),
    (459, "Hunter's Road 2 Base Camp"),
    (460, "Historic 1"),
    (461, "Historic 2"),
    (462, "MezFes Entrance"),
    (463, "Partnyaa Raceway"),
    (464, "Shooting Game"),
    (465, "MezFes Minigame"),
    (466, "MezFes Minigame"),
    (467, "MezFes Minigame"),
    (468, "Can be used as a black void arena"),
    (469, "Minigame Room"),
];

